# Generated by Django 5.1.4 on 2024-12-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Can view vehicle catalog')]},
        ),
    ]
